# Generated by Django 5.0.1 on 2024-01-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=255)),
                ('option_item', models.CharField(max_length=255)),
                ('option_price', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='cafemenu',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
