# Generated by Django 5.0.1 on 2024-01-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cafeoption_alter_cafemenu_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafemenu',
            name='options',
            field=models.JSONField(default=''),
        ),
    ]
