# Generated by Django 5.0.1 on 2024-01-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_cafemenu_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafemenu',
            name='options',
            field=models.JSONField(default={}),
        ),
    ]
