# Generated by Django 5.0.1 on 2024-01-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_cafemenu_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafemenu',
            name='options',
            field=models.JSONField(null=True),
        ),
    ]
