# Generated by Django 5.0.1 on 2024-01-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_cafemenu_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafemenu',
            name='options',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
