# Generated by Django 5.0.1 on 2024-01-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_cafemenu_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafeoption',
            name='option_price',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
    ]
