# Generated by Django 5.0.1 on 2024-01-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_cafeoption_option_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafeoption',
            name='option_price',
            field=models.DecimalField(decimal_places=0, default='', max_digits=10, null=True),
        ),
    ]
