# Generated by Django 5.0.1 on 2024-01-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_cafeoption_option_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafeoption',
            name='option_price',
            field=models.CharField(default='', max_length=255),
        ),
    ]
