# Generated by Django 5.0.1 on 2024-01-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_cafemenu_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafeoption',
            name='option',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cafeoption',
            name='option_item',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cafeoption',
            name='option_price',
            field=models.TextField(),
        ),
    ]
