# Generated by Django 5.0.1 on 2024-01-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_cafeoption_option_alter_cafeoption_option_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeoption',
            name='option_def',
            field=models.TextField(default=''),
        ),
    ]
