# Generated by Django 5.0.1 on 2024-01-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_cafeoption_option_def'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=255)),
                ('order_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('order_quantity', models.IntegerField()),
                ('order_option', models.CharField(max_length=255)),
            ],
        ),
    ]
