# Generated by Django 5.0.1 on 2024-02-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_orderlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientNumberData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('value', models.CharField(max_length=15)),
                ('position', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
