# Generated by Django 5.0.1 on 2024-02-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_clientnumberdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientnumberdata',
            old_name='value',
            new_name='name',
        ),
        migrations.AddField(
            model_name='clientnumberdata',
            name='charge_point',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='clientnumberdata',
            name='current_point',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='clientnumberdata',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientnumberdata',
            name='position',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
