# Generated by Django 5.0.1 on 2024-02-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_rename_value_clientnumberdata_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumberData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('phone_number', models.CharField(max_length=15)),
                ('current_point', models.CharField(blank=True, max_length=15, null=True)),
                ('charge_point', models.CharField(blank=True, max_length=15, null=True)),
                ('position', models.CharField(blank=True, max_length=15, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ClientNumberData',
        ),
    ]
