# Generated by Django 5.0.1 on 2024-02-01 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_phonenumberdata_delete_clientnumberdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhoneNumberData',
            new_name='ClientNumberData',
        ),
    ]
