# Generated by Django 5.0.1 on 2024-02-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_rename_phonenumberdata_clientnumberdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientnumberdata',
            name='value',
            field=models.CharField(default='default_value', max_length=15, null=True),
        ),
    ]
