# Generated by Django 5.0.1 on 2024-02-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_clientnumberdata_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafemenu',
            name='shot',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
    ]
