# Generated by Django 5.0.1 on 2024-02-15 16:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_rename_order_option_orderlist_order_menu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='modified_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
