# Generated by Django 5.0.1 on 2024-02-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_cafemanager_pointlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
