# Generated by Django 5.0.1 on 2024-02-26 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_rename_client_data_pointlist_charge_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointlist',
            name='password',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
