# Generated by Django 5.0.1 on 2024-02-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_pointlist_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
