# Generated by Django 5.0.1 on 2024-02-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_orderlist_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientnumberdata',
            name='current_point',
            field=models.IntegerField(blank=True, max_length=15, null=True),
        ),
    ]
