# Generated by Django 5.0.1 on 2024-03-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_clientnumberdata_current_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientnumberdata',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
